# Generated by Django 4.0.3 on 2022-03-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marker',
            old_name='name',
            new_name='event_name',
        ),
        migrations.AddField(
            model_name='marker',
            name='country_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='event_content',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
