# Generated by Django 4.0.3 on 2022-03-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0003_alter_marker_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='country_name',
            field=models.CharField(max_length=455, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='event_content',
            field=models.CharField(max_length=455, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='event_name',
            field=models.CharField(max_length=455),
        ),
    ]
