# Generated by Django 4.0.3 on 2022-03-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0005_alter_marker_event_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.IntegerField(null=True)),
                ('event_name', models.CharField(max_length=455)),
                ('event_content', models.CharField(max_length=1000, null=True)),
                ('year', models.DateField(null=True)),
                ('country_name', models.CharField(max_length=455, null=True)),
            ],
        )
    ]
