# Generated by Django 4.0.3 on 2022-03-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0006_event_marker_country_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='country_id',
            field=models.IntegerField(null=True),
        ),
    ]
