# Generated by Django 4.0.3 on 2022-04-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0007_marker_country_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=455)),
                ('email', models.EmailField(max_length=455)),
                ('hashed_password', models.CharField(max_length=455)),
            ],
        ),
    ]
